version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"  

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: wiroonchooforg@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "12000:80"